openapi: 3.0.1
info:
  title: Documentación de Carritos
  description: API para gestionar carritos de compra
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/carts:
    post:
      summary: Crear un nuevo carrito
      tags:
        - Carts
      responses:
        201:
          description: Carrito creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        500:
          description: Error al crear el carrito
  /api/carts/{cid}:
    get:
      summary: Obtener un carrito por ID
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Carrito encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        404:
          description: Carrito no encontrado
        500:
          description: Error al obtener el carrito
    put:
      summary: Actualizar un carrito por ID
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Datos actualizados del carrito
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCart'
      responses:
        200:
          description: Carrito actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        404:
          description: Carrito no encontrado
        500:
          description: Error al actualizar el carrito
    delete:
      summary: Vaciar un carrito por ID
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Carrito vaciado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        404:
          description: Carrito no encontrado
        500:
          description: Error al vaciar el carrito
  /api/carts/{cid}/products/{pid}:
    post:
      summary: Agregar un producto al carrito
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
        - name: pid
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Producto agregado al carrito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        404:
          description: Carrito o producto no encontrado
        500:
          description: Error al agregar producto al carrito
    put:
      summary: Actualizar cantidad de un producto en el carrito
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
        - name: pid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Nueva cantidad del producto
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
      responses:
        200:
          description: Cantidad del producto actualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        404:
          description: Carrito o producto no encontrado
        500:
          description: Error al actualizar cantidad del producto en el carrito
    delete:
      summary: Eliminar un producto del carrito
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
        - name: pid
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Producto eliminado del carrito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        404:
          description: Carrito o producto no encontrado
        500:
          description: Error al eliminar producto del carrito
  /api/carts/{cid}/purchase:
    post:
      summary: Comprar el carrito
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Carrito comprado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  purchaseDetails:
                    type: object
        404:
          description: Carrito no encontrado
        500:
          description: Error al comprar el carrito
components:
  schemas:
    Cart:
      type: object
      properties:
        cid:
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/CartProduct'
    CartProduct:
      type: object
      properties:
        pid:
          type: string
        quantity:
          type: integer
    UpdateCart:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/CartProduct'